version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inferencedb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - inference_network

  inference_service:
    build: .
    ports:
      - "8002:8002"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/inferencedb
      - KAFKA_BROKER=kafka:9092
      - DEBUG=True
      - RECREATE_DB=True
      - MAX_RUNNING_CONTAINERS=10
      - CONTAINER_IDLE_TIMEOUT=300
    volumes:
      - ./app:/app/app
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket
      - kafka_events:/app  # Shared volume for Kafka event log
    restart: unless-stopped
    networks:
      - inference_network

volumes:
  db_data:
  kafka_events:
    external: true
    name: upload_service_kafka_events

networks:
  inference_network:
    driver: bridge